### PR TITLE
Fixing the building of hanoidb for R18

### PR DESCRIPTION
**Pull request by a13x**
Some of the dependencies are broken and type definitions are no longer valid for R18.

Fix sext and edown dependency
Fix array() type defs

Change-Id: Ibc2986b690fb81ef9d757fa7b8ba20a994bc8fa2

### CODE REVIEW

**Comment by krestenkrab** [comment]
Any hints for how to fix this across erlang releases?

https://travis-ci.org/krestenkrab/hanoidb/builds/117436445

You should also update the .travis file to include R18.

**Comment by a13x** [comment]
Yeah, I'm going to redo this PR to include  R18 for travis and workout how it would work across releases.. Sorry for a hastily sent PR :)

**Comment by a13x** [comment]
I used rebar's platform_depend trickery.. builds work now, feel free to review! :)

**Comment by krestenkrab** [comment]
Superb. Thanks @a13x!

**Pull request merged**
